### ISSUE TITLE
controller error TypeError: Cannot read properties of undefined (reading 'endsWith')

### ISSUE THREAD

**Issue by besrabasant** [hanayashiki/deepkit-openapi#9]
controller error TypeError: Cannot read properties of undefined (reading 'endsWith')

**Comment by hanayashiki** [comment]
I'm not quite sure how to reproduce this error

**Comment by marcj** [comment]
@besrabasant is there a reason you did not provide the full error stack trace or any other basic information? with this error message alone it is impossible to know where it happened. We can close this if no additional information is provided.

**Comment by besrabasant** [comment]
@marcj I managed to figure out the issue. It seems the issue is fixed in the latest code. However, the latest code is not available in the npm repository. I had to do a local build and refer the packages locally. I believe we can close the issue now.

**Comment by hanayashiki** [comment]
> @marcj I managed to figure out the issue. It seems the issue is fixed in the latest code. However, the latest code is not available in the npm repository. I had to do a local build and refer the packages locally. I believe we can close the issue now.

it's published
